name: Notify Adaimade to Rebuild

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Adaimade image rebuild
        uses: peter-evans/repository-dispatch@v3
        with:
          token: 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
          repository: Adaimade/Adaimade
          event-type: hydrabot-updated
